KNOWLEDGE_BASE = {
    "Programación": [
        {
            "id": "prog_1_1",
            "topic": "Programación",
            "difficulty": 1,
            "context": "Una empresa pequeña necesita un programa para calcular el salario de sus empleados. Se proporcionan las horas trabajadas y el pago por hora.",
            "question": "¿Qué estructura de control es más adecuada para calcular el salario de 10 empleados de forma repetitiva?",
            "options": [{'text': 'Condicional if-else', 'is_correct': False}, {'text': 'Bucle for o while', 'is_correct': True}, {'text': 'Una función recursiva', 'is_correct': False}, {'text': 'Un bloque try-catch', 'is_correct': False}],
            "feedback": {'correct': '¡Correcto! Los bucles son ideales para iterar sobre una colección conocida (como 10 empleados).', 'incorrect': "No es la mejor opción. Recuerda que la palabra clave es 'repetitiva'. Para repetir instrucciones, se usan bucles."},
        },
        {
            "id": "prog_1_2",
            "topic": "Programación",
            "difficulty": 1,
            "context": "Estás diseñando una función que verifica si un número es par.",
            "question": "¿Qué operador aritmético debes usar para determinar el residuo de la división?",
            "options": [{'text': 'Módulo (%)', 'is_correct': True}, {'text': 'División entera (//)', 'is_correct': False}, {'text': 'Exponenciación (**)', 'is_correct': False}, {'text': 'AND lógico (&&)', 'is_correct': False}],
            "feedback": {'correct': '¡Muy bien! El operador módulo te da el residuo. Si numero % 2 == 0, es par.', 'incorrect': 'Incorrecto. Necesitas obtener el residuo de una división, lo cual se hace con el operador módulo (%).'},
        },
        {
            "id": "prog_1_3",
            "topic": "Programación",
            "difficulty": 1,
            "context": "Un sistema guarda la edad de los usuarios en una variable.",
            "question": "¿Qué tipo de dato primitivo es el más adecuado para almacenar la edad en años?",
            "options": [{'text': 'String', 'is_correct': False}, {'text': 'Float', 'is_correct': False}, {'text': 'Boolean', 'is_correct': False}, {'text': 'Integer', 'is_correct': True}],
            "feedback": {'correct': '¡Excelente! La edad en años es un número entero sin decimales.', 'incorrect': "Revisa los tipos de datos. La edad es un número entero, por lo que 'Integer' es lo más adecuado."},
        },
        {
            "id": "prog_1_4",
            "topic": "Programación",
            "difficulty": 1,
            "context": "Se te pide crear una variable que no deba cambiar su valor en toda la ejecución del programa (por ejemplo, el valor de PI).",
            "question": "¿Qué concepto se aplica en este caso?",
            "options": [{'text': 'Variable dinámica', 'is_correct': False}, {'text': 'Constante', 'is_correct': True}, {'text': 'Puntero', 'is_correct': False}, {'text': 'Array', 'is_correct': False}],
            "feedback": {'correct': '¡Correcto! Las constantes son espacios en memoria cuyo valor no se modifica.', 'incorrect': 'Piensa en el significado de la palabra. Si algo no debe cambiar, se le denomina constante.'},
        },
        {
            "id": "prog_1_5",
            "topic": "Programación",
            "difficulty": 1,
            "context": "Tienes una lista de nombres de clientes y necesitas acceder al tercer cliente de la lista.",
            "question": "En la mayoría de los lenguajes, si la lista se llama 'clientes', ¿cómo accedes al tercer elemento?",
            "options": [{'text': 'clientes[3]', 'is_correct': False}, {'text': 'clientes[2]', 'is_correct': True}, {'text': 'clientes.tercero()', 'is_correct': False}, {'text': 'clientes(3)', 'is_correct': False}],
            "feedback": {'correct': '¡Bien hecho! Los índices de los arreglos normalmente comienzan en 0.', 'incorrect': 'Cuidado con los índices. En programación, normalmente empezamos a contar desde el 0.'},
        },
        {
            "id": "prog_2_1",
            "topic": "Programación",
            "difficulty": 2,
            "context": "Un desarrollador ha creado una clase 'Vehículo' con atributos como marca y modelo. Luego, crea una nueva clase 'Coche' que hereda de 'Vehículo'.",
            "question": "¿Qué principio de la Programación Orientada a Objetos se está aplicando?",
            "options": [{'text': 'Encapsulamiento', 'is_correct': False}, {'text': 'Polimorfismo', 'is_correct': False}, {'text': 'Herencia', 'is_correct': True}, {'text': 'Abstracción', 'is_correct': False}],
            "feedback": {'correct': '¡Exacto! La herencia permite que una clase hija obtenga propiedades y métodos de una clase padre.', 'incorrect': 'Cuando una clase se basa en otra para reutilizar su código, estamos hablando de Herencia.'},
        },
        {
            "id": "prog_2_2",
            "topic": "Programación",
            "difficulty": 2,
            "context": "Estás analizando un algoritmo de ordenamiento que divide la lista por la mitad recursivamente hasta tener elementos individuales, y luego los fusiona en orden.",
            "question": "¿A qué algoritmo se hace referencia?",
            "options": [{'text': 'Bubble Sort', 'is_correct': False}, {'text': 'Merge Sort', 'is_correct': True}, {'text': 'Insertion Sort', 'is_correct': False}, {'text': 'Selection Sort', 'is_correct': False}],
            "feedback": {'correct': '¡Correcto! Merge Sort aplica el paradigma de divide y vencerás.', 'incorrect': 'El patrón de dividir por la mitad y fusionar (merge) es característico del Merge Sort.'},
        },
        {
            "id": "prog_2_3",
            "topic": "Programación",
            "difficulty": 2,
            "context": "En el desarrollo de una API REST, necesitas enviar datos confidenciales como contraseñas desde el cliente al servidor de forma segura.",
            "question": "¿Qué método HTTP debes usar para enviar esta información en el cuerpo de la petición?",
            "options": [{'text': 'GET', 'is_correct': False}, {'text': 'POST', 'is_correct': True}, {'text': 'DELETE', 'is_correct': False}, {'text': 'HEAD', 'is_correct': False}],
            "feedback": {'correct': '¡Así es! POST envía datos en el cuerpo (body) de la solicitud, siendo más seguro que GET.', 'incorrect': 'Recuerda que GET expone los parámetros en la URL. Para enviar datos confidenciales se recomienda POST.'},
        },
        {
            "id": "prog_2_4",
            "topic": "Programación",
            "difficulty": 2,
            "context": "Un programa se queda colgado y no responde. Al revisar el código ves un bucle 'while(true)' sin ninguna instrucción de ruptura o cambio de estado.",
            "question": "¿Cómo se conoce a este problema?",
            "options": [{'text': 'Desbordamiento de pila (Stack Overflow)', 'is_correct': False}, {'text': 'Fuga de memoria (Memory Leak)', 'is_correct': False}, {'text': 'Bucle infinito', 'is_correct': True}, {'text': 'Condición de carrera (Race Condition)', 'is_correct': False}],
            "feedback": {'correct': '¡Bien! Un bucle que nunca evalúa a falso se ejecutará para siempre.', 'incorrect': "Si la condición del bucle nunca cambia a falso y no hay 'break', tienes un Bucle infinito."},
        },
        {
            "id": "prog_2_5",
            "topic": "Programación",
            "difficulty": 2,
            "context": "Estás diseñando un módulo donde necesitas restringir el acceso directo a ciertas variables internas de un objeto, obligando al uso de getters y setters.",
            "question": "¿Qué concepto de POO estás utilizando?",
            "options": [{'text': 'Polimorfismo', 'is_correct': False}, {'text': 'Encapsulamiento', 'is_correct': True}, {'text': 'Herencia Múltiple', 'is_correct': False}, {'text': 'Sobrecarga de métodos', 'is_correct': False}],
            "feedback": {'correct': '¡Correcto! El encapsulamiento protege el estado interno del objeto.', 'incorrect': 'La protección y ocultación de datos internos mediante modificadores de acceso se llama Encapsulamiento.'},
        },
        {
            "id": "prog_3_1",
            "topic": "Programación",
            "difficulty": 3,
            "context": "Se te asigna optimizar una función recursiva que calcula la serie de Fibonacci, la cual tarda mucho por recalcular los mismos valores repetidamente.",
            "question": "¿Qué técnica de optimización debes implementar para guardar los resultados previos en memoria y evitar cálculos redundantes?",
            "options": [{'text': 'Backtracking', 'is_correct': False}, {'text': 'Memoization (Programación Dinámica)', 'is_correct': True}, {'text': 'Greedy Algorithms', 'is_correct': False}, {'text': 'Divide and Conquer', 'is_correct': False}],
            "feedback": {'correct': '¡Excelente! La memoización guarda resultados para reutilizarlos, reduciendo drásticamente la complejidad temporal.', 'incorrect': 'Almacenar resultados previos para no repetir cálculos se conoce como Memoización (una técnica de Programación Dinámica).'},
        },
        {
            "id": "prog_3_2",
            "topic": "Programación",
            "difficulty": 3,
            "context": "En un entorno de microservicios, varias solicitudes simultáneas intentan modificar el saldo de una misma cuenta bancaria al mismo tiempo, provocando inconsistencias en el saldo final.",
            "question": "¿A qué problema de concurrencia nos referimos?",
            "options": [{'text': 'Deadlock (Abrazo mortal)', 'is_correct': False}, {'text': 'Race Condition (Condición de carrera)', 'is_correct': True}, {'text': 'Starvation (Inanición)', 'is_correct': False}, {'text': 'Livelock', 'is_correct': False}],
            "feedback": {'correct': '¡Muy bien! Una condición de carrera ocurre cuando el resultado depende del orden impredecible de ejecución de los hilos.', 'incorrect': 'Cuando el orden en que se ejecutan los hilos concurrentes afecta el resultado, ocurre una Race Condition.'},
        },
        {
            "id": "prog_3_3",
            "topic": "Programación",
            "difficulty": 3,
            "context": "Estás evaluando la complejidad temporal de un algoritmo usando la Notación Big-O. El algoritmo contiene un bucle anidado dentro de otro bucle iterando sobre los mismos 'n' elementos.",
            "question": "¿Cuál es la complejidad temporal asintótica del algoritmo en el peor de los casos?",
            "options": [{'text': 'O(log n)', 'is_correct': False}, {'text': 'O(n)', 'is_correct': False}, {'text': 'O(n log n)', 'is_correct': False}, {'text': 'O(n^2)', 'is_correct': True}],
            "feedback": {'correct': "¡Perfecto! Dos bucles anidados sobre 'n' elementos resultan en complejidad cuadrática O(n^2).", 'incorrect': "Si por cada 'n' elemento, se vuelve a iterar sobre 'n' elementos, se realiza n * n operaciones. La respuesta es O(n^2)."},
        },
        {
            "id": "prog_3_4",
            "topic": "Programación",
            "difficulty": 3,
            "context": "Al implementar un árbol de búsqueda binaria (BST), notas que los datos insertados están pre-ordenados, lo que degrada el árbol en una lista enlazada.",
            "question": "¿Qué tipo de estructura de datos resuelve este problema manteniendo el árbol balanceado automáticamente?",
            "options": [{'text': 'Árbol AVL o Red-Black Tree', 'is_correct': True}, {'text': 'Cola de Prioridad (Heap)', 'is_correct': False}, {'text': 'Grafo Dirigido Acíclico', 'is_correct': False}, {'text': 'Tabla Hash (Hash Map)', 'is_correct': False}],
            "feedback": {'correct': '¡Correcto! Los árboles AVL y Rojo-Negro se rebalancean solos durante la inserción/eliminación.', 'incorrect': 'Para mantener un árbol balanceado independientemente del orden de inserción, necesitas usar Árboles AVL o Red-Black Trees.'},
        },
        {
            "id": "prog_3_5",
            "topic": "Programación",
            "difficulty": 3,
            "context": "Tienes un sistema distribuido donde debes asegurar que todas las transacciones se completen o ninguna lo haga, manteniendo la atomicidad.",
            "question": "¿Qué patrón o protocolo es comúnmente usado para manejar transacciones distribuidas?",
            "options": [{'text': 'Protocolo de validación en 2 fases (Two-Phase Commit)', 'is_correct': True}, {'text': 'Algoritmo de Dijkstra', 'is_correct': False}, {'text': 'Patrón Singleton', 'is_correct': False}, {'text': 'Circuit Breaker', 'is_correct': False}],
            "feedback": {'correct': '¡Exacto! Two-Phase Commit (2PC) coordina transacciones atómicas a lo largo de nodos distribuidos.', 'incorrect': 'El protocolo que prepara todos los nodos y luego confirma, garantizando atomicidad en sistemas distribuidos, es el Two-Phase Commit.'},
        },
    ],
    "Seguridad Informática": [
        {
            "id": "sec_1_1",
            "topic": "Seguridad Informática",
            "difficulty": 1,
            "context": "Un usuario recibe un correo electrónico que parece ser de su banco, pidiéndole que ingrese su contraseña en un enlace adjunto.",
            "question": "¿Qué tipo de ataque informático describe este escenario?",
            "options": [{'text': 'Phishing', 'is_correct': True}, {'text': 'Ransomware', 'is_correct': False}, {'text': 'DDoS', 'is_correct': False}, {'text': 'Spyware', 'is_correct': False}],
            "feedback": {'correct': '¡Correcto! El phishing busca engañar al usuario haciéndose pasar por una entidad confiable.', 'incorrect': 'No. Este ataque se basa en la suplantación de identidad por correo, conocido como Phishing.'},
        },
        {
            "id": "sec_1_2",
            "topic": "Seguridad Informática",
            "difficulty": 1,
            "context": "Necesitas proteger los archivos de tu computadora para que no se pierdan en caso de un fallo del disco duro.",
            "question": "¿Cuál es la medida preventiva más básica e importante?",
            "options": [{'text': 'Instalar un firewall', 'is_correct': False}, {'text': 'Realizar copias de seguridad (Backups)', 'is_correct': True}, {'text': 'Usar modo incógnito', 'is_correct': False}, {'text': 'Desactivar el Wi-Fi', 'is_correct': False}],
            "feedback": {'correct': '¡Exacto! Los backups son esenciales para la recuperación de datos.', 'incorrect': 'Para evitar la pérdida permanente de datos por fallos de hardware, se deben hacer Backups.'},
        },
        {
            "id": "sec_1_3",
            "topic": "Seguridad Informática",
            "difficulty": 1,
            "context": "Quieres crear una contraseña segura para tu correo electrónico.",
            "question": "¿Cuál de las siguientes opciones es la más segura?",
            "options": [{'text': '12345678', 'is_correct': False}, {'text': 'password123', 'is_correct': False}, {'text': 'M!P4ssw0rd_S3gura#24', 'is_correct': True}, {'text': 'tunombre1990', 'is_correct': False}],
            "feedback": {'correct': '¡Muy bien! Una contraseña fuerte combina mayúsculas, minúsculas, números y símbolos.', 'incorrect': 'Las contraseñas seguras deben tener longitud, símbolos, números y letras mezcladas.'},
        },
        {
            "id": "sec_1_4",
            "topic": "Seguridad Informática",
            "difficulty": 1,
            "context": "Tu computadora de repente muestra un mensaje exigiendo un pago en criptomonedas para desbloquear tus archivos.",
            "question": "¿De qué tipo de malware fuiste víctima?",
            "options": [{'text': 'Adware', 'is_correct': False}, {'text': 'Troyano', 'is_correct': False}, {'text': 'Ransomware', 'is_correct': True}, {'text': 'Gusano', 'is_correct': False}],
            "feedback": {'correct': "¡Correcto! El Ransomware 'secuestra' la información pidiendo un rescate.", 'incorrect': 'El malware que secuestra archivos y exige un rescate se llama Ransomware.'},
        },
        {
            "id": "sec_1_5",
            "topic": "Seguridad Informática",
            "difficulty": 1,
            "context": "Navegando en internet, notas que la URL de un sitio web comienza con 'https://'.",
            "question": "¿Qué indica la letra 's' en HTTPS?",
            "options": [{'text': 'Secure (Seguro)', 'is_correct': True}, {'text': 'System (Sistema)', 'is_correct': False}, {'text': 'Server (Servidor)', 'is_correct': False}, {'text': 'Speed (Velocidad)', 'is_correct': False}],
            "feedback": {'correct': '¡Bien! Indica que la conexión está cifrada mediante SSL/TLS.', 'incorrect': "La 's' significa 'Secure', indicando cifrado en la transmisión de datos."},
        },
        {
            "id": "sec_2_1",
            "topic": "Seguridad Informática",
            "difficulty": 2,
            "context": "Estás implementando un sistema de inicio de sesión que pide contraseña y, además, un código enviado por SMS al celular del usuario.",
            "question": "¿Cómo se conoce a esta práctica de seguridad?",
            "options": [{'text': 'Autenticación de Dos Factores (2FA)', 'is_correct': True}, {'text': 'Cifrado Asimétrico', 'is_correct': False}, {'text': 'Control de Acceso Basado en Roles (RBAC)', 'is_correct': False}, {'text': 'Single Sign-On (SSO)', 'is_correct': False}],
            "feedback": {'correct': "¡Correcto! Combinar 'algo que sabes' con 'algo que tienes' es 2FA.", 'incorrect': 'Pedir más de un elemento para verificar la identidad se llama Autenticación de Múltiples Factores o 2FA.'},
        },
        {
            "id": "sec_2_2",
            "topic": "Seguridad Informática",
            "difficulty": 2,
            "context": "Un atacante intercepta la comunicación entre tu computadora y un servidor bancario, leyendo y modificando los mensajes en tiempo real.",
            "question": "¿Cómo se llama este tipo de ataque?",
            "options": [{'text': 'Man in the Middle (MitM)', 'is_correct': True}, {'text': 'Denegación de Servicio (DoS)', 'is_correct': False}, {'text': 'Fuerza Bruta', 'is_correct': False}, {'text': 'Inyección SQL', 'is_correct': False}],
            "feedback": {'correct': "¡Exacto! El atacante se sitúa 'en medio' de la comunicación.", 'incorrect': 'Interceptar y alterar comunicaciones secretamente es un ataque de Man in the Middle (MitM).'},
        },
        {
            "id": "sec_2_3",
            "topic": "Seguridad Informática",
            "difficulty": 2,
            "context": "Estás asegurando una red wifi y debes elegir un protocolo de seguridad.",
            "question": "¿Cuál es el estándar más actual y seguro recomendado para redes Wi-Fi?",
            "options": [{'text': 'WEP', 'is_correct': False}, {'text': 'WPA', 'is_correct': False}, {'text': 'WPA3', 'is_correct': True}, {'text': 'WPS', 'is_correct': False}],
            "feedback": {'correct': '¡Muy bien! WPA3 es el estándar más moderno y seguro.', 'incorrect': 'Actualmente, WPA3 provee la encriptación más fuerte para redes inalámbricas.'},
        },
        {
            "id": "sec_2_4",
            "topic": "Seguridad Informática",
            "difficulty": 2,
            "context": "Debes almacenar las contraseñas de los usuarios en una base de datos.",
            "question": "¿Qué proceso criptográfico se debe aplicar a las contraseñas antes de guardarlas?",
            "options": [{'text': 'Cifrado simétrico', 'is_correct': False}, {'text': 'Codificación Base64', 'is_correct': False}, {'text': 'Hashing (ej. SHA-256 + Salt)', 'is_correct': True}, {'text': 'Compresión ZIP', 'is_correct': False}],
            "feedback": {'correct': '¡Correcto! El Hashing es irreversible, lo ideal para contraseñas.', 'incorrect': 'Las contraseñas nunca deben guardarse en texto claro ni codificadas, deben usar Hashing.'},
        },
        {
            "id": "sec_2_5",
            "topic": "Seguridad Informática",
            "difficulty": 2,
            "context": "Un administrador de red configura reglas que permiten o deniegan el tráfico de red basado en direcciones IP y puertos.",
            "question": "¿Qué componente de seguridad está configurando?",
            "options": [{'text': 'Antivirus', 'is_correct': False}, {'text': 'Firewall', 'is_correct': True}, {'text': 'VPN', 'is_correct': False}, {'text': 'Proxy Inverso', 'is_correct': False}],
            "feedback": {'correct': '¡Bien! El Firewall es la barrera que filtra el tráfico de red.', 'incorrect': 'El componente encargado de bloquear o permitir tráfico a nivel de red es el Firewall.'},
        },
        {
            "id": "sec_3_1",
            "topic": "Seguridad Informática",
            "difficulty": 3,
            "context": "En un ataque de inyección SQL, el atacante introduce código SQL malicioso a través de un campo de formulario.",
            "question": "¿Cuál es la técnica de programación más efectiva para prevenir esto en el backend?",
            "options": [{'text': 'Limpiar etiquetas HTML', 'is_correct': False}, {'text': 'Usar Consultas Preparadas (Prepared Statements)', 'is_correct': True}, {'text': 'Ocultar errores de base de datos', 'is_correct': False}, {'text': 'Bloquear la IP del atacante', 'is_correct': False}],
            "feedback": {'correct': '¡Excelente! Las consultas preparadas separan los datos del código ejecutable.', 'incorrect': 'La defensa estándar contra SQL Injection son las Consultas Preparadas.'},
        },
        {
            "id": "sec_3_2",
            "topic": "Seguridad Informática",
            "difficulty": 3,
            "context": "Un algoritmo de cifrado utiliza dos claves diferentes: una pública para cifrar y una privada para descifrar.",
            "question": "¿A qué paradigma criptográfico corresponde esto?",
            "options": [{'text': 'Criptografía Simétrica', 'is_correct': False}, {'text': 'Esteganografía', 'is_correct': False}, {'text': 'Criptografía Asimétrica (o de clave pública)', 'is_correct': True}, {'text': 'Funciones Hash', 'is_correct': False}],
            "feedback": {'correct': '¡Muy bien! Algoritmos como RSA utilizan criptografía asimétrica.', 'incorrect': 'El uso de pares de claves pública/privada pertenece a la Criptografía Asimétrica.'},
        },
        {
            "id": "sec_3_3",
            "topic": "Seguridad Informática",
            "difficulty": 3,
            "context": "Una organización es víctima de un ataque que inunda sus servidores web con tráfico basura desde miles de dispositivos infectados (botnet).",
            "question": "¿Qué nombre recibe este ataque?",
            "options": [{'text': 'DDoS (Distributed Denial of Service)', 'is_correct': True}, {'text': 'Spoofing', 'is_correct': False}, {'text': 'Cross-Site Scripting (XSS)', 'is_correct': False}, {'text': 'APT (Advanced Persistent Threat)', 'is_correct': False}],
            "feedback": {'correct': '¡Correcto! DDoS usa múltiples fuentes para sobrecargar un servicio.', 'incorrect': 'Un ataque distribuido de denegación de servicio se conoce como DDoS.'},
        },
        {
            "id": "sec_3_4",
            "topic": "Seguridad Informática",
            "difficulty": 3,
            "context": "Estás realizando una prueba de penetración (pentesting) y utilizas una herramienta para capturar y analizar paquetes de red en tránsito.",
            "question": "¿Qué tipo de herramienta estás utilizando?",
            "options": [{'text': 'Escáner de vulnerabilidades', 'is_correct': False}, {'text': 'Sniffer de paquetes (Ej. Wireshark)', 'is_correct': True}, {'text': 'Debugger', 'is_correct': False}, {'text': 'Gestor de contraseñas', 'is_correct': False}],
            "feedback": {'correct': '¡Exacto! Los sniffers capturan tráfico a bajo nivel.', 'incorrect': 'Para interceptar y analizar paquetes a nivel de red, se utiliza un Sniffer (analizador de protocolos).'},
        },
        {
            "id": "sec_3_5",
            "topic": "Seguridad Informática",
            "difficulty": 3,
            "context": "Almacenas un certificado digital en un servidor. Este certificado asegura que el servidor es quien dice ser.",
            "question": "¿Qué entidad externa y confiable emite estos certificados?",
            "options": [{'text': 'ISP (Proveedor de Internet)', 'is_correct': False}, {'text': 'DNS (Sistema de Nombres de Dominio)', 'is_correct': False}, {'text': 'Autoridad de Certificación (CA)', 'is_correct': True}, {'text': 'Firewall de Aplicaciones Web (WAF)', 'is_correct': False}],
            "feedback": {'correct': '¡Perfecto! Las CA validan identidades y firman los certificados.', 'incorrect': 'Las entidades encargadas de emitir y revocar certificados digitales son las Autoridades de Certificación (CA).'},
        },
    ],
    "Análisis Forense": [
        {
            "id": "for_1_1",
            "topic": "Análisis Forense",
            "difficulty": 1,
            "context": "Llegas a la escena de un incidente y encuentras una computadora encendida que fue utilizada por el sospechoso.",
            "question": "¿Qué tipo de datos se perderán irremediablemente si apagas la computadora sin precaución?",
            "options": [{'text': 'Datos en el disco duro', 'is_correct': False}, {'text': 'Archivos ocultos', 'is_correct': False}, {'text': 'Datos volátiles en la memoria RAM', 'is_correct': True}, {'text': 'El sistema operativo', 'is_correct': False}],
            "feedback": {'correct': '¡Correcto! La memoria RAM se borra al cortar el suministro eléctrico.', 'incorrect': 'Al apagar un equipo, los datos volátiles alojados en la memoria RAM se pierden.'},
        },
        {
            "id": "for_1_2",
            "topic": "Análisis Forense",
            "difficulty": 1,
            "context": "Para asegurar que una evidencia digital (ej. un disco duro) no sea modificada durante su examen.",
            "question": "¿Qué dispositivo físico de seguridad se debe emplear?",
            "options": [{'text': 'Bloqueador de escritura (Write Blocker)', 'is_correct': True}, {'text': 'Un cable USB encriptado', 'is_correct': False}, {'text': 'Un switch de red', 'is_correct': False}, {'text': 'Un disco de estado sólido', 'is_correct': False}],
            "feedback": {'correct': '¡Exacto! El bloqueador impide que el sistema operativo forense escriba en el disco original.', 'incorrect': 'Para preservar la integridad, se utiliza hardware llamado Bloqueador de escritura (Write Blocker).'},
        },
        {
            "id": "for_1_3",
            "topic": "Análisis Forense",
            "difficulty": 1,
            "context": "Al recopilar un dispositivo móvil como evidencia, necesitas aislarlo de la red para que no sea borrado remotamente.",
            "question": "¿Qué método sencillo y rápido aísla el dispositivo de señales inalámbricas?",
            "options": [{'text': 'Envolverlo en papel aluminio', 'is_correct': False}, {'text': 'Colocarlo en una Bolsa de Faraday', 'is_correct': True}, {'text': 'Ponerlo en modo vibración', 'is_correct': False}, {'text': 'Apagar el Bluetooth', 'is_correct': False}],
            "feedback": {'correct': '¡Muy bien! Las bolsas de Faraday bloquean las ondas electromagnéticas.', 'incorrect': 'Una Bolsa de Faraday evita que el dispositivo reciba o emita señales de red.'},
        },
        {
            "id": "for_1_4",
            "topic": "Análisis Forense",
            "difficulty": 1,
            "context": "Has incautado un disco duro. El primer paso técnico antes de analizarlo es crear una copia bit a bit.",
            "question": "¿Cómo se le llama a esta copia exacta?",
            "options": [{'text': 'Copia de seguridad incremental', 'is_correct': False}, {'text': 'Imagen Forense', 'is_correct': True}, {'text': 'Clonación virtual', 'is_correct': False}, {'text': 'Snapshot', 'is_correct': False}],
            "feedback": {'correct': '¡Correcto! La imagen forense captura incluso el espacio no asignado del disco.', 'incorrect': 'Una copia bit a bit para análisis se denomina Imagen Forense.'},
        },
        {
            "id": "for_1_5",
            "topic": "Análisis Forense",
            "difficulty": 1,
            "context": "Se requiere mantener un registro documentado de todas las personas que manejaron la evidencia desde su recolección hasta el juicio.",
            "question": "¿Cómo se llama este documento legal y procedimental?",
            "options": [{'text': 'Cadena de Custodia', 'is_correct': True}, {'text': 'Acta de Nacimiento', 'is_correct': False}, {'text': 'Reporte de Incidentes', 'is_correct': False}, {'text': 'Manifiesto de Carga', 'is_correct': False}],
            "feedback": {'correct': '¡Excelente! La Cadena de Custodia garantiza que la evidencia no fue alterada.', 'incorrect': 'El registro ininterrumpido del manejo de evidencia se llama Cadena de Custodia.'},
        },
        {
            "id": "for_2_1",
            "topic": "Análisis Forense",
            "difficulty": 2,
            "context": "Al generar una imagen forense de un disco, necesitas comprobar matemáticamente que la copia es idéntica al original.",
            "question": "¿Qué mecanismo criptográfico utilizas para verificar la integridad de la imagen?",
            "options": [{'text': 'Cifrado RSA', 'is_correct': False}, {'text': 'Firmas Digitales', 'is_correct': False}, {'text': 'Funciones Hash (MD5, SHA-1, SHA-256)', 'is_correct': True}, {'text': 'Codificación Base64', 'is_correct': False}],
            "feedback": {'correct': '¡Muy bien! Comparar los hashes del original y la copia garantiza su igualdad.', 'incorrect': 'El cálculo y comparación de Hashes se usa para garantizar la integridad de los datos.'},
        },
        {
            "id": "for_2_2",
            "topic": "Análisis Forense",
            "difficulty": 2,
            "context": "Durante la investigación de un documento de Word, extraes información sobre el autor, la fecha de creación y la aplicación usada.",
            "question": "¿Cómo se denomina a este conjunto de 'datos sobre los datos'?",
            "options": [{'text': 'Registros del sistema (Logs)', 'is_correct': False}, {'text': 'Metadatos', 'is_correct': True}, {'text': 'Archivos temporales', 'is_correct': False}, {'text': 'Esteganografía', 'is_correct': False}],
            "feedback": {'correct': '¡Correcto! Los metadatos proveen contexto crucial sin alterar el archivo principal.', 'incorrect': 'La información oculta que describe las características de un archivo se llama Metadatos.'},
        },
        {
            "id": "for_2_3",
            "topic": "Análisis Forense",
            "difficulty": 2,
            "context": "Estás analizando la línea de tiempo de un sistema Windows para ver qué programas se ejecutaron recientemente.",
            "question": "¿Qué artefacto del sistema operativo Windows es fundamental para encontrar esta configuración y actividad?",
            "options": [{'text': 'Carpeta System32', 'is_correct': False}, {'text': 'El Registro de Windows (Registry)', 'is_correct': True}, {'text': 'El Administrador de Tareas', 'is_correct': False}, {'text': 'El archivo hosts', 'is_correct': False}],
            "feedback": {'correct': '¡Exacto! El Registro almacena extensas huellas de la actividad del usuario y sistema.', 'incorrect': 'El Registro de Windows es una mina de oro forense con historiales y configuraciones.'},
        },
        {
            "id": "for_2_4",
            "topic": "Análisis Forense",
            "difficulty": 2,
            "context": "Alguien borró un archivo intencionalmente. Como investigador forense, sabes que el sistema operativo no borra los datos inmediatamente.",
            "question": "¿Dónde es más probable encontrar los fragmentos de ese archivo borrado?",
            "options": [{'text': 'En la memoria caché del procesador', 'is_correct': False}, {'text': 'En el espacio no asignado (Unallocated Space)', 'is_correct': True}, {'text': 'En el archivo de paginación', 'is_correct': False}, {'text': 'En el sector de arranque', 'is_correct': False}],
            "feedback": {'correct': '¡Bien! El SO solo marca el espacio como disponible, pero los datos siguen allí hasta sobrescribirse.', 'incorrect': 'Cuando un archivo se borra, sus clusters pasan a formar parte del Espacio no asignado.'},
        },
        {
            "id": "for_2_5",
            "topic": "Análisis Forense",
            "difficulty": 2,
            "context": "Analizas una fotografía digital y encuentras la ubicación GPS exacta donde fue tomada oculta dentro del archivo.",
            "question": "¿En qué formato de metadatos de imagen se guarda esta información típicamente?",
            "options": [{'text': 'EXIF (Exchangeable Image File Format)', 'is_correct': True}, {'text': 'PNG-Alpha', 'is_correct': False}, {'text': 'JPEG-XR', 'is_correct': False}, {'text': 'TIFF-Tags', 'is_correct': False}],
            "feedback": {'correct': '¡Correcto! Los metadatos EXIF almacenan parámetros de la cámara y GPS.', 'incorrect': 'La información de ubicación y cámara en imágenes se almacena comúnmente en formato EXIF.'},
        },
        {
            "id": "for_3_1",
            "topic": "Análisis Forense",
            "difficulty": 3,
            "context": "Un atacante intentó ocultar un archivo secreto dentro del código de una imagen inofensiva modificando los bits menos significativos (LSB).",
            "question": "¿Qué técnica forense debes aplicar para descubrir esta información?",
            "options": [{'text': 'Desofuscación', 'is_correct': False}, {'text': 'Criptoanálisis', 'is_correct': False}, {'text': 'Estegoanálisis (detección de Esteganografía)', 'is_correct': True}, {'text': 'Análisis de Malware', 'is_correct': False}],
            "feedback": {'correct': '¡Excelente! La esteganografía oculta datos a plena vista, y el estegoanálisis los revela.', 'incorrect': 'La técnica de ocultar información dentro de otro archivo es esteganografía, combatida con el Estegoanálisis.'},
        },
        {
            "id": "for_3_2",
            "topic": "Análisis Forense",
            "difficulty": 3,
            "context": "Estás analizando la memoria RAM de un equipo infectado buscando procesos inyectados o malware sin archivo (fileless).",
            "question": "¿Qué herramienta de código abierto es considerada un estándar en la industria para el análisis forense de memoria?",
            "options": [{'text': 'Autopsy', 'is_correct': False}, {'text': 'EnCase', 'is_correct': False}, {'text': 'Volatility', 'is_correct': True}, {'text': 'Nmap', 'is_correct': False}],
            "feedback": {'correct': '¡Muy bien! Volatility Framework es líder en análisis de volcados de memoria.', 'incorrect': 'Para extraer artefactos de volcados de memoria RAM se utiliza ampliamente Volatility.'},
        },
        {
            "id": "for_3_3",
            "topic": "Análisis Forense",
            "difficulty": 3,
            "context": "El sistema de archivos NTFS utiliza una base de datos central para llevar el control de todos los archivos y directorios del volumen.",
            "question": "¿Cómo se llama este componente crítico de NTFS?",
            "options": [{'text': 'Master File Table (MFT)', 'is_correct': True}, {'text': 'File Allocation Table (FAT)', 'is_correct': False}, {'text': 'Inodes', 'is_correct': False}, {'text': 'Superbloque', 'is_correct': False}],
            "feedback": {'correct': '¡Correcto! La MFT contiene registros de cada archivo, incluyendo sus metadatos de tiempo (MAC times).', 'incorrect': 'En NTFS, la estructura maestra que mapea los archivos es la MFT.'},
        },
        {
            "id": "for_3_4",
            "topic": "Análisis Forense",
            "difficulty": 3,
            "context": "En la recolección de evidencia en vivo, el 'Orden de Volatilidad' dicta qué datos capturar primero.",
            "question": "¿Según el RFC 3227, cuál es el orden correcto del más volátil al menos volátil?",
            "options": [{'text': 'Disco duro, Registros/Caché, RAM, Medios removibles', 'is_correct': False}, {'text': 'Registros/Caché, RAM, Tráfico de Red, Disco Duro', 'is_correct': True}, {'text': 'RAM, Disco Duro, Tráfico de Red, Registros', 'is_correct': False}, {'text': 'Tráfico de Red, Disco Duro, RAM, Caché', 'is_correct': False}],
            "feedback": {'correct': '¡Exacto! Siempre se capturan primero los registros de CPU y memoria caché, luego la RAM.', 'incorrect': 'Debes ir de lo que se borra instantáneamente (Caché/Registros) a lo más permanente (Discos).'},
        },
        {
            "id": "for_3_5",
            "topic": "Análisis Forense",
            "difficulty": 3,
            "context": "Un atacante alteró un archivo binario pero logró mantener el mismo hash MD5 original usando un ataque criptográfico.",
            "question": "¿Cómo se conoce a este tipo de fallo criptográfico donde dos entradas distintas producen el mismo hash?",
            "options": [{'text': 'Colisión Hash', 'is_correct': True}, {'text': 'Avalancha Hash', 'is_correct': False}, {'text': 'Desbordamiento de búfer', 'is_correct': False}, {'text': 'Fuerza Bruta Reversa', 'is_correct': False}],
            "feedback": {'correct': '¡Perfecto! Debido a las colisiones, MD5 y SHA-1 ya no son seguros y se prefiere SHA-256.', 'incorrect': 'Cuando dos archivos diferentes generan el mismo hash, se ha producido una Colisión.'},
        },
    ],
    "Arquitectura de Computadoras": [
        {
            "id": "arq_1_1",
            "topic": "Arquitectura de Computadoras",
            "difficulty": 1,
            "context": "El 'cerebro' de la computadora se encarga de procesar las instrucciones y coordinar los componentes.",
            "question": "¿Cuál es el nombre de este componente principal?",
            "options": [{'text': 'Unidad de Procesamiento Gráfico (GPU)', 'is_correct': False}, {'text': 'Memoria RAM', 'is_correct': False}, {'text': 'Placa Base (Motherboard)', 'is_correct': False}, {'text': 'Unidad Central de Procesamiento (CPU)', 'is_correct': True}],
            "feedback": {'correct': '¡Correcto! La CPU es el procesador principal del sistema.', 'incorrect': 'El componente principal que ejecuta instrucciones es la CPU.'},
        },
        {
            "id": "arq_1_2",
            "topic": "Arquitectura de Computadoras",
            "difficulty": 1,
            "context": "Necesitas más espacio temporal para que el sistema mantenga abiertas varias aplicaciones a la vez sin ponerse lento.",
            "question": "¿Qué componente de hardware debes ampliar?",
            "options": [{'text': 'Disco Duro', 'is_correct': False}, {'text': 'Fuente de Poder', 'is_correct': False}, {'text': 'Memoria RAM', 'is_correct': True}, {'text': 'Tarjeta de Red', 'is_correct': False}],
            "feedback": {'correct': '¡Muy bien! La RAM es la memoria de trabajo volátil a corto plazo.', 'incorrect': 'Para manejar más aplicaciones abiertas simultáneamente necesitas más Memoria RAM.'},
        },
        {
            "id": "arq_1_3",
            "topic": "Arquitectura de Computadoras",
            "difficulty": 1,
            "context": "Todos los componentes de hardware (CPU, RAM, discos, periféricos) se conectan a un mismo circuito impreso.",
            "question": "¿Cómo se llama este componente integrador?",
            "options": [{'text': 'Tarjeta Madre (Motherboard)', 'is_correct': True}, {'text': 'Bus de Datos', 'is_correct': False}, {'text': 'Fuente de Poder', 'is_correct': False}, {'text': 'Gabinete (Chasis)', 'is_correct': False}],
            "feedback": {'correct': '¡Exacto! La Tarjeta Madre provee las vías de comunicación para el hardware.', 'incorrect': 'La placa principal donde se conecta todo es la Tarjeta Madre.'},
        },
        {
            "id": "arq_1_4",
            "topic": "Arquitectura de Computadoras",
            "difficulty": 1,
            "context": "Las computadoras modernas utilizan el sistema binario para representar datos.",
            "question": "¿Cuál es la unidad más pequeña de información en este sistema?",
            "options": [{'text': 'Byte', 'is_correct': False}, {'text': 'Bit', 'is_correct': True}, {'text': 'Hertz', 'is_correct': False}, {'text': 'Pixel', 'is_correct': False}],
            "feedback": {'correct': '¡Correcto! Un bit puede ser un 0 o un 1.', 'incorrect': 'La unidad mínima que puede tomar valores 0 o 1 es el Bit.'},
        },
        {
            "id": "arq_1_5",
            "topic": "Arquitectura de Computadoras",
            "difficulty": 1,
            "context": "Al ensamblar una PC de alto rendimiento para videojuegos, instalas un componente dedicado exclusivamente a procesar polígonos y texturas 3D.",
            "question": "¿Qué componente es?",
            "options": [{'text': 'Procesador multinúcleo', 'is_correct': False}, {'text': 'Tarjeta Gráfica (GPU)', 'is_correct': True}, {'text': 'Disco SSD M.2', 'is_correct': False}, {'text': 'Memoria VRAM', 'is_correct': False}],
            "feedback": {'correct': '¡Bien! La GPU descarga a la CPU del trabajo de renderizado gráfico.', 'incorrect': 'Para aceleración gráfica dedicada se utiliza una Tarjeta Gráfica o GPU.'},
        },
        {
            "id": "arq_2_1",
            "topic": "Arquitectura de Computadoras",
            "difficulty": 2,
            "context": "Dentro del ciclo de instrucción de la CPU (Fetch, Decode, Execute, Store).",
            "question": "¿Qué componente específico se encarga de realizar operaciones matemáticas y operaciones lógicas (AND, OR)?",
            "options": [{'text': 'Unidad de Control (CU)', 'is_correct': False}, {'text': 'Unidad Aritmético Lógica (ALU)', 'is_correct': True}, {'text': 'Registros', 'is_correct': False}, {'text': 'Memoria Caché', 'is_correct': False}],
            "feedback": {'correct': '¡Correcto! La ALU ejecuta los cálculos en el procesador.', 'incorrect': 'La subunidad encargada de las matemáticas es la ALU.'},
        },
        {
            "id": "arq_2_2",
            "topic": "Arquitectura de Computadoras",
            "difficulty": 2,
            "context": "La CPU es muchísimo más rápida que la memoria RAM. Para no desperdiciar ciclos esperando datos de la RAM, se añade una memoria muy veloz dentro del propio procesador.",
            "question": "¿Cómo se llama esta memoria intermedia?",
            "options": [{'text': 'Memoria Virtual', 'is_correct': False}, {'text': 'Registros de propósito general', 'is_correct': False}, {'text': 'Memoria Caché (L1/L2/L3)', 'is_correct': True}, {'text': 'Memoria ROM', 'is_correct': False}],
            "feedback": {'correct': '¡Muy bien! La Caché reduce la latencia de acceso a los datos más usados.', 'incorrect': 'La memoria rápida ubicada entre la CPU y la RAM es la Memoria Caché.'},
        },
        {
            "id": "arq_2_3",
            "topic": "Arquitectura de Computadoras",
            "difficulty": 2,
            "context": "Al encender la computadora, un programa básico inicializa el hardware y busca el sistema operativo para cargarlo.",
            "question": "¿Cómo se llama el firmware estándar moderno que reemplazó a la BIOS tradicional?",
            "options": [{'text': 'CMOS', 'is_correct': False}, {'text': 'UEFI', 'is_correct': True}, {'text': 'Bootloader', 'is_correct': False}, {'text': 'GRUB', 'is_correct': False}],
            "feedback": {'correct': '¡Exacto! UEFI (Unified Extensible Firmware Interface) es más seguro y rápido que la BIOS heredada.', 'incorrect': 'El firmware moderno que maneja el arranque seguro y hardware complejo es UEFI.'},
        },
        {
            "id": "arq_2_4",
            "topic": "Arquitectura de Computadoras",
            "difficulty": 2,
            "context": "Estás leyendo las especificaciones de un procesador y ves que tiene un 'Bus de Datos de 64 bits'.",
            "question": "¿Qué significa esto principalmente?",
            "options": [{'text': 'Puede transferir 64 bits de información al mismo tiempo', 'is_correct': True}, {'text': 'Su velocidad de reloj es de 64 GHz', 'is_correct': False}, {'text': 'Solo puede usar programas antiguos de 32 bits', 'is_correct': False}, {'text': 'Tiene 64 núcleos de procesamiento', 'is_correct': False}],
            "feedback": {'correct': '¡Correcto! El ancho de bus indica cuántos bits viajan en paralelo.', 'incorrect': 'El ancho del bus de datos define el tamaño de la palabra que la CPU procesa o transfiere en un ciclo.'},
        },
        {
            "id": "arq_2_5",
            "topic": "Arquitectura de Computadoras",
            "difficulty": 2,
            "context": "Quieres aumentar drásticamente la velocidad de arranque y de carga de aplicaciones en una laptop vieja.",
            "question": "¿Qué reemplazo de hardware proporciona el mayor impacto de rendimiento en I/O?",
            "options": [{'text': 'Aumentar la RAM', 'is_correct': False}, {'text': 'Cambiar el disco HDD mecánico por una unidad SSD', 'is_correct': True}, {'text': 'Instalar una mejor refrigeración', 'is_correct': False}, {'text': 'Actualizar el firmware de la batería', 'is_correct': False}],
            "feedback": {'correct': '¡Bien! Los SSD eliminan los tiempos de búsqueda mecánica de los discos tradicionales.', 'incorrect': 'Un SSD es órdenes de magnitud más rápido en lectura/escritura que un HDD tradicional.'},
        },
        {
            "id": "arq_3_1",
            "topic": "Arquitectura de Computadoras",
            "difficulty": 3,
            "context": "El diseño clásico de computadoras establece que los datos y las instrucciones del programa se almacenan en la misma memoria unificada.",
            "question": "¿A qué arquitectura clásica nos referimos?",
            "options": [{'text': 'Arquitectura Harvard', 'is_correct': False}, {'text': 'Arquitectura de Von Neumann', 'is_correct': True}, {'text': 'Arquitectura RISC', 'is_correct': False}, {'text': 'Arquitectura ARM', 'is_correct': False}],
            "feedback": {'correct': '¡Excelente! Von Neumann introdujo el concepto del programa almacenado en memoria compartida con datos.', 'incorrect': 'La arquitectura que unifica buses de memoria para datos e instrucciones es la de Von Neumann.'},
        },
        {
            "id": "arq_3_2",
            "topic": "Arquitectura de Computadoras",
            "difficulty": 3,
            "context": "Para mejorar el rendimiento, una CPU comienza a ejecutar una segunda instrucción antes de que la primera haya terminado (traslape de fases).",
            "question": "¿Cómo se llama esta técnica de optimización a nivel de hardware?",
            "options": [{'text': 'Pipelining (Segmentación de cauce)', 'is_correct': True}, {'text': 'Overclocking', 'is_correct': False}, {'text': 'Hyperthreading', 'is_correct': False}, {'text': 'Ejecución fuera de orden (Out-of-order execution)', 'is_correct': False}],
            "feedback": {'correct': '¡Muy bien! El pipelining divide el ciclo de instrucción en etapas paralelas.', 'incorrect': 'La segmentación (Pipelining) permite a la CPU procesar múltiples instrucciones en distintas fases al mismo tiempo.'},
        },
        {
            "id": "arq_3_3",
            "topic": "Arquitectura de Computadoras",
            "difficulty": 3,
            "context": "Un procesador decide basarse en un conjunto reducido y simple de instrucciones que se ejecutan en un solo ciclo de reloj, muy usado en dispositivos móviles (ej. ARM).",
            "question": "¿Qué filosofía de diseño del conjunto de instrucciones (ISA) utiliza?",
            "options": [{'text': 'CISC (Complex Instruction Set Computer)', 'is_correct': False}, {'text': 'RISC (Reduced Instruction Set Computer)', 'is_correct': True}, {'text': 'VLIW (Very Long Instruction Word)', 'is_correct': False}, {'text': 'x86-64', 'is_correct': False}],
            "feedback": {'correct': '¡Correcto! RISC prioriza instrucciones simples y rápidas frente a las complejas de CISC.', 'incorrect': 'Un ISA basado en instrucciones reducidas de tamaño fijo es RISC.'},
        },
        {
            "id": "arq_3_4",
            "topic": "Arquitectura de Computadoras",
            "difficulty": 3,
            "context": "Para transferir grandes bloques de datos de un disco duro a la memoria RAM sin ocupar a la CPU en cada bit transferido, se utiliza un controlador especial.",
            "question": "¿Cómo se llama este mecanismo de transferencia directa?",
            "options": [{'text': 'Interrupt Request (IRQ)', 'is_correct': False}, {'text': 'Direct Memory Access (DMA)', 'is_correct': True}, {'text': 'Polling', 'is_correct': False}, {'text': 'Memory-Mapped I/O', 'is_correct': False}],
            "feedback": {'correct': '¡Exacto! El DMA libera a la CPU de operaciones masivas de I/O.', 'incorrect': 'El Acceso Directo a Memoria (DMA) permite a los periféricos comunicarse con la RAM sin intervenir la CPU.'},
        },
        {
            "id": "arq_3_5",
            "topic": "Arquitectura de Computadoras",
            "difficulty": 3,
            "context": "Un problema clásico en arquitecturas multicore es asegurar que si un núcleo modifica una variable en su caché L1, los demás núcleos vean el valor actualizado.",
            "question": "¿A qué problema nos referimos?",
            "options": [{'text': 'Coherencia de Caché (Cache Coherence)', 'is_correct': True}, {'text': 'Paginación de Memoria', 'is_correct': False}, {'text': 'Fallos de Caché (Cache Miss)', 'is_correct': False}, {'text': 'Fragmentación Interna', 'is_correct': False}],
            "feedback": {'correct': '¡Perfecto! Protocolos como MESI garantizan la coherencia de los datos entre cachés.', 'incorrect': 'El reto de mantener los datos sincronizados en múltiples cachés locales se llama Coherencia de Caché.'},
        },
    ],
    "Bases de Datos": [
        {
            "id": "bd_1_1",
            "topic": "Bases de Datos",
            "difficulty": 1,
            "context": "Estás diseñando una tabla para almacenar información de usuarios y necesitas un identificador único para cada registro.",
            "question": "¿Qué concepto de bases de datos se utiliza para este propósito?",
            "options": [{'text': 'Llave Primaria (Primary Key)', 'is_correct': True}, {'text': 'Llave Foránea (Foreign Key)', 'is_correct': False}, {'text': 'Índice (Index)', 'is_correct': False}, {'text': 'Vista (View)', 'is_correct': False}],
            "feedback": {'correct': '¡Correcto! La llave primaria identifica de forma única cada fila.', 'incorrect': 'El identificador único por excelencia de un registro es la Llave Primaria.'},
        },
        {
            "id": "bd_1_2",
            "topic": "Bases de Datos",
            "difficulty": 1,
            "context": "Necesitas extraer todos los registros de una tabla llamada 'empleados'.",
            "question": "¿Cuál es la instrucción SQL correcta?",
            "options": [{'text': 'GET * FROM empleados', 'is_correct': False}, {'text': 'SELECT * FROM empleados', 'is_correct': True}, {'text': 'EXTRACT * FROM empleados', 'is_correct': False}, {'text': 'FETCH * FROM empleados', 'is_correct': False}],
            "feedback": {'correct': '¡Muy bien! SELECT es la instrucción estándar para consultas.', 'incorrect': 'En SQL, la palabra reservada para obtener datos es SELECT.'},
        },
        {
            "id": "bd_1_3",
            "topic": "Bases de Datos",
            "difficulty": 1,
            "context": "Te piden agregar un nuevo cliente a la base de datos de la empresa.",
            "question": "¿Qué sentencia SQL debes utilizar?",
            "options": [{'text': 'UPDATE', 'is_correct': False}, {'text': 'INSERT', 'is_correct': True}, {'text': 'ADD', 'is_correct': False}, {'text': 'CREATE', 'is_correct': False}],
            "feedback": {'correct': '¡Exacto! INSERT permite agregar nuevos registros.', 'incorrect': 'Para insertar nuevas filas a una tabla existente se usa INSERT.'},
        },
        {
            "id": "bd_1_4",
            "topic": "Bases de Datos",
            "difficulty": 1,
            "context": "Un sistema gestiona la información agrupándola en tablas con filas y columnas, relacionándolas entre sí.",
            "question": "¿Cómo se clasifica este tipo de base de datos?",
            "options": [{'text': 'Relacional (RDBMS)', 'is_correct': True}, {'text': 'Basada en Grafos', 'is_correct': False}, {'text': 'Documental (NoSQL)', 'is_correct': False}, {'text': 'Jerárquica', 'is_correct': False}],
            "feedback": {'correct': '¡Correcto! El uso de tablas interconectadas es característico del modelo Relacional.', 'incorrect': 'El modelo basado en tablas con filas y columnas se llama Relacional.'},
        },
        {
            "id": "bd_1_5",
            "topic": "Bases de Datos",
            "difficulty": 1,
            "context": "Descubres un error en el correo de un usuario y necesitas corregirlo en la base de datos.",
            "question": "¿Qué comando SQL debes usar?",
            "options": [{'text': 'ALTER', 'is_correct': False}, {'text': 'MODIFY', 'is_correct': False}, {'text': 'UPDATE', 'is_correct': True}, {'text': 'CHANGE', 'is_correct': False}],
            "feedback": {'correct': '¡Bien hecho! UPDATE permite modificar registros existentes.', 'incorrect': 'Para actualizar datos de un registro existente usamos UPDATE.'},
        },
        {
            "id": "bd_2_1",
            "topic": "Bases de Datos",
            "difficulty": 2,
            "context": "Tienes una tabla 'pedidos' que contiene un campo 'id_cliente'. Este campo hace referencia al ID de la tabla 'clientes'.",
            "question": "¿Qué tipo de clave es 'id_cliente' en la tabla 'pedidos'?",
            "options": [{'text': 'Llave Candidata', 'is_correct': False}, {'text': 'Llave Compuesta', 'is_correct': False}, {'text': 'Llave Foránea (Foreign Key)', 'is_correct': True}, {'text': 'Llave Alternativa', 'is_correct': False}],
            "feedback": {'correct': '¡Correcto! Las llaves foráneas enlazan tablas distintas.', 'incorrect': 'Cuando un campo referencia la llave primaria de otra tabla, se llama Llave Foránea.'},
        },
        {
            "id": "bd_2_2",
            "topic": "Bases de Datos",
            "difficulty": 2,
            "context": "Necesitas mostrar una lista de clientes junto con los nombres de los productos que compraron, información que está en tablas separadas.",
            "question": "¿Qué operación relacional SQL debes utilizar?",
            "options": [{'text': 'JOIN', 'is_correct': True}, {'text': 'UNION', 'is_correct': False}, {'text': 'MERGE', 'is_correct': False}, {'text': 'GROUP BY', 'is_correct': False}],
            "feedback": {'correct': '¡Muy bien! JOIN combina columnas de una o más tablas basándose en campos comunes.', 'incorrect': 'La cláusula para cruzar y relacionar registros de múltiples tablas es JOIN.'},
        },
        {
            "id": "bd_2_3",
            "topic": "Bases de Datos",
            "difficulty": 2,
            "context": "Las consultas a tu tabla de millones de usuarios por nombre son muy lentas. Necesitas optimizar las lecturas sin modificar las consultas.",
            "question": "¿Qué estructura de la base de datos deberías crear sobre la columna 'nombre'?",
            "options": [{'text': 'Un Trigger', 'is_correct': False}, {'text': 'Un Índice (Index)', 'is_correct': True}, {'text': 'Una Vista Materializada', 'is_correct': False}, {'text': 'Una Secuencia', 'is_correct': False}],
            "feedback": {'correct': '¡Exacto! Los índices aceleran la recuperación de datos.', 'incorrect': 'Un Índice actúa como el índice de un libro, acelerando las búsquedas significativamente.'},
        },
        {
            "id": "bd_2_4",
            "topic": "Bases de Datos",
            "difficulty": 2,
            "context": "Estás diseñando la estructura de la base de datos y aplicas reglas para evitar la redundancia y dependencias anómalas de los datos (ej. Primera, Segunda y Tercera Forma).",
            "question": "¿Cómo se conoce a este proceso de diseño?",
            "options": [{'text': 'Abstracción', 'is_correct': False}, {'text': 'Desnormalización', 'is_correct': False}, {'text': 'Normalización', 'is_correct': True}, {'text': 'Fragmentación', 'is_correct': False}],
            "feedback": {'correct': '¡Correcto! La normalización organiza la base de datos para reducir la redundancia.', 'incorrect': 'El proceso sistemático para asegurar que las tablas no tengan datos duplicados innecesarios es la Normalización.'},
        },
        {
            "id": "bd_2_5",
            "topic": "Bases de Datos",
            "difficulty": 2,
            "context": "Deseas agrupar las ventas totales por mes usando la cláusula GROUP BY, y solo mostrar los meses cuyas ventas superen los $10,000.",
            "question": "¿Qué cláusula SQL debes usar para filtrar grupos agregados?",
            "options": [{'text': 'WHERE', 'is_correct': False}, {'text': 'HAVING', 'is_correct': True}, {'text': 'FILTER', 'is_correct': False}, {'text': 'ORDER BY', 'is_correct': False}],
            "feedback": {'correct': '¡Bien! HAVING se utiliza en lugar de WHERE para funciones de agregación.', 'incorrect': "WHERE filtra registros individuales, pero HAVING se utiliza para filtrar agrupaciones de 'GROUP BY'."},
        },
        {
            "id": "bd_3_1",
            "topic": "Bases de Datos",
            "difficulty": 3,
            "context": "En un sistema bancario, una transferencia de fondos descuenta dinero de una cuenta y lo abona en otra. Si hay un fallo de energía a la mitad, los cambios deben deshacerse por completo.",
            "question": "¿Qué propiedad de las transacciones garantiza que se ejecuten 'todo o nada'?",
            "options": [{'text': 'Consistencia', 'is_correct': False}, {'text': 'Durabilidad', 'is_correct': False}, {'text': 'Aislamiento', 'is_correct': False}, {'text': 'Atomicidad', 'is_correct': True}],
            "feedback": {'correct': '¡Excelente! La Atomicidad (la A en ACID) asegura operaciones indivisibles.', 'incorrect': "La regla del 'todo o nada' en las transacciones es la propiedad de Atomicidad."},
        },
        {
            "id": "bd_3_2",
            "topic": "Bases de Datos",
            "difficulty": 3,
            "context": "Necesitas obtener TODOS los registros de la tabla 'clientes', independientemente de si tienen o no registros relacionados en la tabla 'pedidos'.",
            "question": "¿Qué tipo de Join debes ejecutar?",
            "options": [{'text': 'INNER JOIN', 'is_correct': False}, {'text': 'LEFT JOIN (o RIGHT JOIN)', 'is_correct': True}, {'text': 'CROSS JOIN', 'is_correct': False}, {'text': 'SELF JOIN', 'is_correct': False}],
            "feedback": {'correct': '¡Muy bien! Un OUTER JOIN (como LEFT JOIN) devuelve todo de la primera tabla incluso si no hay coincidencias.', 'incorrect': 'INNER JOIN solo trae los que coinciden. Para traer todos los de un lado se usa LEFT JOIN.'},
        },
        {
            "id": "bd_3_3",
            "topic": "Bases de Datos",
            "difficulty": 3,
            "context": "Estás desarrollando una aplicación altamente escalable con datos desestructurados en formato JSON que no encajan bien en tablas rígidas.",
            "question": "¿Qué tipo de base de datos deberías elegir?",
            "options": [{'text': 'Base de Datos Relacional (PostgreSQL)', 'is_correct': False}, {'text': 'Base de Datos Orientada a Documentos (MongoDB, NoSQL)', 'is_correct': True}, {'text': 'Base de Datos en Memoria (Redis)', 'is_correct': False}, {'text': 'Base de Datos Columnar (Cassandra)', 'is_correct': False}],
            "feedback": {'correct': '¡Exacto! Las BD orientadas a documentos son ideales para datos semiestructurados como JSON.', 'incorrect': 'Para datos en JSON de esquema flexible, una BD Orientada a Documentos (NoSQL) es la mejor opción.'},
        },
        {
            "id": "bd_3_4",
            "topic": "Bases de Datos",
            "difficulty": 3,
            "context": "Tienes una serie de sentencias SQL complejas que se ejecutan frecuentemente con diferentes parámetros. Para mejorar la seguridad y la velocidad, decides precompilarlas y guardarlas en el servidor de la BD.",
            "question": "¿Qué objeto de base de datos estás creando?",
            "options": [{'text': 'Procedimiento Almacenado (Stored Procedure)', 'is_correct': True}, {'text': 'Trigger', 'is_correct': False}, {'text': 'Función Escalar', 'is_correct': False}, {'text': 'Vista Materializada', 'is_correct': False}],
            "feedback": {'correct': '¡Perfecto! Los procedimientos almacenados guardan lógica precompilada en la BD.', 'incorrect': 'Un lote de instrucciones guardadas y precompiladas en el motor de BD es un Procedimiento Almacenado.'},
        },
        {
            "id": "bd_3_5",
            "topic": "Bases de Datos",
            "difficulty": 3,
            "context": "En un sistema concurrente, para evitar que una transacción lea datos que otra transacción aún no ha 'commiteado' (dirty reads), debes configurar el nivel de aislamiento.",
            "question": "¿Cuál es el nivel de aislamiento más estricto que previene incluso las lecturas fantasmas?",
            "options": [{'text': 'Read Uncommitted', 'is_correct': False}, {'text': 'Read Committed', 'is_correct': False}, {'text': 'Repeatable Read', 'is_correct': False}, {'text': 'Serializable', 'is_correct': True}],
            "feedback": {'correct': '¡Correcto! Serializable hace que las transacciones se ejecuten de manera secuencial.', 'incorrect': 'El nivel máximo de aislamiento que simula una ejecución secuencial es Serializable.'},
        },
    ],
}

def get_topics():
    return list(KNOWLEDGE_BASE.keys())

import random
import copy

def get_questions_for_round(topic, difficulty, asked_ids=None):
    if asked_ids is None:
        asked_ids = []
    if topic not in KNOWLEDGE_BASE:
        return []
        
    # Filtrar preguntas que no se hayan hecho
    unasked = [q for q in KNOWLEDGE_BASE[topic] if q['id'] not in asked_ids]
    
    # Primero buscamos en la dificultad solicitada
    base_questions = [q for q in unasked if q['difficulty'] == difficulty]
    
    # Si no hay suficientes (5), rellenamos con otras dificultades del mismo tema
    if len(base_questions) < 5:
        other_questions = [q for q in unasked if q['difficulty'] != difficulty]
        random.shuffle(other_questions)
        # Completar hasta 5 (o menos si ya no hay)
        needed = 5 - len(base_questions)
        base_questions.extend(other_questions[:needed])
        
    questions = copy.deepcopy(base_questions[:5])
    random.shuffle(questions)
    for q in questions:
        random.shuffle(q['options'])
    return questions
